version: '3'
services:
  jlama-coordinator:
    image: jlama
    restart: always
    container_name: jlama-coordinator
    ports:
      - "8080:8080"
    environment:
      - JLAMA_JVM_ARGS_EXTRA=-Xmx1g -Djava.net.preferIPv4Stack=true
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: 1
    command:
      - cluster-coordinator
      - --threads=4
      - --worker-count=16
      - /models/Llama-2-7b-chat-hf-jlama-Q4/
    volumes:
      - "./models:/models"
  jlama-worker:
    image: jlama
    restart: always
    environment:
      - JLAMA_JVM_ARGS_EXTRA=-Xmx500M -Djava.net.preferIPv4Stack=true -Djlama.use_hostname_as_workerid=true
    deploy:
      mode: replicated
      replicas: 16
      resources:
        limits:
          cpus: 1
          memory: 500m
    command:
      - cluster-worker
      - --threads=1
      - --host=jlama-coordinator
      - /models/Llama-2-7b-chat-hf-jlama-Q4/
    volumes:
      - "./models:/models"
